/**
 * Created by JimBarrows on 7/3/16.
 */

export const UserEventNames = {
	REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE"
	, REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS"
	, USER_LOGGED_IN: "USER_LOGGED_IN"
	, USER_LOGGED_OUT: "USER_LOGGED_OUT"
	, USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE"
	, USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE"
};

export const ContentEventNames = {
	CONTENT_FETCH_SUCCESS: "CONTENT_FETCH_SUCCESS",
	CONTENT_FETCH_FAILURE: "CONTENT_FETCH_FAILURE",
	CONTENT_CREATE_SUCCESS: "CONTENT_CREATE_SUCCESS",
	CONTENT_CREATE_FAILURE: "CONTENT_CREATE_FAILURE",
	CONTENT_UPDATE_SUCCESS: "CONTENT_UPDATE_SUCCESS",
	CONTENT_UPDATE_FAILURE: "CONTENT_UPDATE_FAILURE",
	CONTENT_DELETE_SUCCESS: "CONTENT_DELETE_SUCCESS",
	CONTENT_DELETE_FAILURE: "CONTENT_DELETE_FAILURE",
};