/**
 * Created by JimBarrows on 7/3/16.
 */

export const CampaignEvent = {
	CLEAR: "CLEAR_CAMPAIGN",
	CREATE_FAILURE: "CREATE_CAMPAIGN_FAILURE",
	CREATE_SUCCESS: "CREATE_CAMPAIGN_SUCCESS",
	LOAD_CAMPAIGN_FAILURE: "LOAD_CAMPAIGN_FAILURE",
	LOAD_CAMPAIGN_SUCCESS: "LOAD_CAMPAIGN_SUCCESS",
	LOAD_LIST_FAILURE: "LOAD_CAMPAIGN_LIST_FAILURE",
	LOAD_LIST_SUCCESS: "LOAD_CAMPAIGN_LIST_SUCCESS",
	REMOVE_CAMPAIGN_FAILURE: "REMOVE_CAMPAIGN_FAILURE",
	REMOVE_CAMPAIGN_SUCCESS: "REMOVE_CAMPAIGN_SUCCESS",
	UPDATE_FAILURE: "UPDATE_CAMPAIGN_FAILURE",
	UPDATE_SUCCESS: "UPDATE_CAMPAIGN_SUCCESS"
};

export const ContentEventNames = {
	CONTENT_FETCH_SUCCESS: "CONTENT_FETCH_SUCCESS",
	CONTENT_FETCH_FAILURE: "CONTENT_FETCH_FAILURE",
	CONTENT_CREATE_SUCCESS: "CONTENT_CREATE_SUCCESS",
	CONTENT_CREATE_FAILURE: "CONTENT_CREATE_FAILURE",
	CONTENT_UPDATE_SUCCESS: "CONTENT_UPDATE_SUCCESS",
	CONTENT_UPDATE_FAILURE: "CONTENT_UPDATE_FAILURE",
	CONTENT_DELETE_SUCCESS: "CONTENT_DELETE_SUCCESS",
	CONTENT_DELETE_FAILURE: "CONTENT_DELETE_FAILURE",
};
export const UserEventNames    = {
	REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE"
	, REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS"
	, UPDATE_ACCOUNT: "UPDATE_ACCOUNT"
	, UPDATE_ACCOUNT_FAILURE: "UPDATE_ACCOUNT_FAILURE"
	, USER_LOGGED_IN: "USER_LOGGED_IN"
	, USER_LOGGED_OUT: "USER_LOGGED_OUT"
	, USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE"
	, USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE"

};

